server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/myapi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:25}
    protocol: smtp
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings

app:
  jwt:
    secret: "${JWT_SECRET:#~?Xb-:ga7H2SFCG4]UA(Y?]f8XN]~M4&}Eg,_i[j}575};29uqgp-tMB:C}F,68}"
    accessTtlMinutes: ${JWT_ACCESS_TTL_MIN:15}
    refreshTtlDays: ${JWT_REFRESH_TTL_DAYS:14}

  passwordReset:
    ttlMinutes: ${PASSWORD_RESET_TTL_MIN:15}
    linkBase: ${PASSWORD_RESET_LINK_BASE:https://doctorsapp.cfolks.pl/reset-password?token=}

  mail:
    enabled: ${MAIL_ENABLED:true}
    from: ${MAIL_FROM:noreply@doctorsapp.cfolks.pl}
    replyTo: ${MAIL_REPLY_TO:noreply@doctorsapp.cfolks.pl}
